/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsConfig = {
  aws_project_region: "eu-north-1",
  aws_cognito_identity_pool_id:
    "eu-north-1:e802ffbb-5981-41b3-bda9-fe20d5d6f480",
  aws_cognito_region: "eu-north-1",
  aws_user_pools_id: "eu-north-1_ksHqGykK7",
  aws_user_pools_web_client_id: "5i8900dta48q73gns6006v3u1c",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsConfig;
